<?php

namespace Imie\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnServiceRepository extends EntityRepository
{
}
